### ISSUE TITLE
News4ward Beiträge

### ISSUE THREAD

**Issue by Schuberth1980** [psi-4ward/news4ward_categories#10]
Es ist ein Fehler aufgetreten

Was ist das Problem?

Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.

Wie kann ich das Problem lösen?

Öffnen Sie die Datei system/logs/error.log und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte). Sie können auch folgende Zeile in die lokale Konfigurationsdatei einfügen und diese Seite neu laden:

$GLOBALS['TL_CONFIG']['displayErrors'] = true;
Beachten Sie jedoch, dass in diesem Fall jeder die Fehlermeldungen auf Ihrer Webseite sehen kann!

in der genannte Datei steht zur dies Meldung:

Es ist ein Fehler aufgetreten

Was ist das Problem?

Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.

Wie kann ich das Problem lösen?

Öffnen Sie die Datei system/logs/error.log und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte). Sie können auch folgende Zeile in die lokale Konfigurationsdatei einfügen und diese Seite neu laden:

[05-Apr-2015 17:59:17 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Column 'author' cannot be null (INSERT INTO tl_news4ward_article (author, social, start, pid, sorting, tstamp) VALUES (NULL, 'a:4:{i:0;s:8:\"facebook\";i:1;s:7:\"twitter\";i:2;s:6:\"google\";i:3;s:5:\"email\";}', 1428249557, 1, 128, 0))' thrown in /Applications/MAMP/htdocs/ordner/ordner2/system/modules/core/library/Contao/Database/Statement.php on line 293
#0 /Applications/MAMP/htdocs/ordner/ordner2/system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 /Applications/MAMP/htdocs/ordner/ordner2/system/modules/core/drivers/DC_Table.php(660): Contao\Database\Statement->execute()
#2 /Applications/MAMP/htdocs/ordner/ordner2/system/modules/core/classes/Backend.php(622): Contao\DC_Table->create()
#3 /Applications/MAMP/htdocs/ordner/ordner2/system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('news4ward')
#4 /Applications/MAMP/htdocs/ordner/ordner2/contao/main.php(20): Contao\BackendMain->run()
#5 {main}
 
Ich bitte Hilfe. Vielen Dank
Schuberth

**Comment by frontendschlampe** [comment]
author could not be null: Ist ein Autor angegeben? Weil da kommt der Fehler her.

**Comment by Schuberth1980** [comment]
Bis jetzt bin ich der einzige Author (Administrator) muss ich das irgendwo anders explizit für das hier genannte Modul zuweisen ? Den ich komme ja nichtmal in die neue Beiträge rein bzw. geschweige ein erst zu erstellen. Nur die Beitragsarchive konnte ich erstellen.

**Comment by frontendschlampe** [comment]
ähm ... wo und wann kommt der Fehler? Mit welcher Contao Version und mit welcher Version der Extension? Welche weiteren Extensions sind installiert? Wird das ER oder die Paketverwaltung (Composer) genutzt?

**Comment by Schuberth1980** [comment]
Wo dieser Fehler herkommt :+1: 
bei der Nutzung des Modul News4award 
nach dem ich einen Beitragsarchiv erstellt haben und ein neuen Beitrag erstellen will.
Ich verwende die Paketverwaltung

folgende Module / Erweiterungen sind bei mir installiert:


	contao			
metapackage		contao/core	3.4.5		
contao-community-alliance			
contao-module		
contao-community-alliance/composer-client	0.15.1	
contao-legacy			
	legacy-contao-module		contao-legacy/backupdb	3.2.2.9004		

contao-legacy/easy_themes 
⤷ terminal42/contao-easy_themes	2.1.2.9005	
	legacy-contao-module		contao-legacy/linkslist	1.1.3.9009	
 	
legacy-contao-module		contao-legacy/news4ward 
⤷ psi/news4ward	2.1.0.9010	 
	legacy-contao-module		contao-legacy/zad_docman	0.9.3.3004-beta

**Comment by frontendschlampe** [comment]
hmmm, aber ich sehe das Modul news4ward_categories gar nicht als installiert - des weiteren solltest du nicht das contao-legacy Modul installieren, sondern direkt das darunter empfohlene von Packagist - das könnte u.U. aktueller sein

**Comment by Schuberth1980** [comment]
Ich habe nun Online & Lokal folgende News4ward Module installiert:

			psi			
	contao-module		psi/news4ward	2.2.3	 Verankerung auf Version aufheben.	 Paket entfernen
	contao-module		psi/news4ward_archive-menu	2.0.8	 Auf Version verankern	 Paket entfernen
	contao-module		psi/news4ward_author-menu	2.0.2	 Auf Version verankern	 Paket entfernen
	contao-module		psi/news4ward_categories	2.1.0	 Auf Version verankern	 Paket entfernen
	contao-module		psi/news4ward_multicategories	1.0.4	 Auf Version verankern	 Paket entfernen
	contao-module		psi/news4ward_tags	2.1.1	 Auf Version verankern	 Paket entfernen

übrigens habe ich festgestellt,  in dem Beitragarchiv zwei Menüpunkte gibt, die Kategorien heissen.  Ist das so gewünscht ? Den in dem ein steht immer das selbe, wie in dem anderen. und wenn ich diese Kategorie verdoppelte,  bleibt immer nur eine Kategorien in beiden Kategorien-Punkte  bestehen und die andere Kategorienbezeichnungen verschwinden. Das ist doch wahrscheinlich so nicht gewünscht oder ?

**Comment by frontendschlampe** [comment]
ja ... du solltest nur ein Modul installieren: entweder categories oder multi-categories - auf jeden Fall davon schon mal eins deinstallieren

**Comment by psi-4ward** [comment]
1. categories und multicategories sollten sich nicht in die Quere kommen, außer das man verwirrend viele "Kategorie" Filter/Felder hat
2. das `author` Feld hat eigentlich nichts mit Kategorien zu tun und sollte auch nie NULL sein.

@Schuberth1980 welche Contao Version? Hast du die neusten News4ward Versionen? Kannst du mir nen Dump der Seite schicken oder einen SSH Zugang geben und genau beschreiben wie ich den Fehler reproduzieren kann?
